name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  async: ^2.13.0
  flutter:
    sdk: flutter
  material_color_utilities: ^0.11.1
  provider: ^6.1.4
  vm_service: ^15.0.0
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  custom_radio_grouped_button: ^2.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  sqflite_common_ffi: ^2.3.5
  universal_io: ^2.2.2
  http: ^1.3.0

## dev_dependencies:
##  flutter_test:
##    sdk: flutter
##  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

intl: any
provider: ^5.0.0
dev_dependencies:
  json_serializable: ^6.9.5

